### ISSUE TITLE
Getting zero value from Jetson Nano

### ISSUE THREAD

**Issue by kaloomte** [tatobari/hx711py#40]
Hi 

When i use  HX711 and 4 load cell for my project with Jetson Nano 4GB, i'm getting zero value, however same wiring method with arduino nano or RPi 4 it works. I'm wondering is this library not compatible with Jetson Nano?

**Comment by tatobari** [comment]
Hey, I never tried it on Jetson Nano. Not sure if it uses the same libraries. Sorry!

**Comment by jung-youjin** [comment]
@kaloomte Hi! Did you solve this?
