### ISSUE TITLE
reading data problem

### ISSUE THREAD

**Issue by overdull** [tatobari/hx711py#5]
can you please help me...
sometimes it works and it is showing real data. 😃 
but most of the time it is something like this... it starts with small negative number and decrease...
i can put weight like on attachment but it is still decreasing. 😢 
<img width="498" alt="screen shot 2016-09-29 at 22 22 45" src="https://cloud.githubusercontent.com/assets/22530639/18970865/4d1758b4-8693-11e6-855b-084dc4f10267.png">

**Comment by tatobari** [comment]
Hi!
A few questions first:

- Are those readings with no weight at all or did you put some weight?
- Did you follow the configuration process explained on example.py to set up the `refference_unit`?
- What kind of load cell are you using? Can you post a picture?

For some reason, the HX711 tends to "warm up" when it's  just been powered. It takes about 10 minutes to get a stable reading. I have absolutely no idea why this happens. It's probably something real "electronics" people know and know how to newutralize. That's not my case.

We'll sort it out. I've made lot's of improvements to the vode and it seems to be working much better now.

Tato
