### ISSUE TITLE
Reading on beaglebone Black rev C

### ISSUE THREAD

**Issue by panditjiNE** [tatobari/hx711py#8]
I run the code on beaglebone Black and I am getting only zeros @ output, what am I supposed to do!

**Comment by tatobari** [comment]
Sorry, I can't really help. The code is designed for Raspberry, I'm not aware of what a beagblebone is.

However, looks like you're probably not setting up the correct pins when instantiating the class.

**Comment by panditjiNE** [comment]
Ok dear...
