### ISSUE TITLE
Latest HX711 Library

### ISSUE THREAD

**Issue by zerox1212** [tatobari/hx711py#9]
So is this the latest library to your knowledge? Or is it better to use the one in the readme?
https://gist.github.com/iilxy/f8b95cd039759b18edcdfe60684a6b8f

**Comment by tatobari** [comment]
Hey Andrew,
I know that this library I've ported works. It's bein used on more than
2000 devices out on the street on a IoT project.

Tato

**Comment by zerox1212** [comment]
Might want to update the readme, it's confusing on which code to use since you can't directly compare this repo with the gist.

**Comment by tatobari** [comment]
Done. Thanks for the advice!
